### PR TITLE
XTSequel is another great GUI tool for PostgreSQL

### PR DESCRIPTION
**Pull request by bmpro**
Very fast! Simple! Fast launch! Autosaves your queries!

### CODE REVIEW

**Comment by jakob** [comment]
Are you the developer of this app?

I wanted to check out the app, but the fact that the apps website has an invalid TLS certificate made me a bit suspicious.

Also, your Github account profile looks a bit like a spam account.

I wish you the best of luck with your app, but I'm not going to merge this PR for now.

**Comment by bmpro** [comment]
> Are you the developer of this app?
> 
> I wanted to check out the app, but the fact that the apps website has an invalid TLS certificate made me a bit suspicious.
> 
> Also, your Github account profile looks a bit like a spam account.
> 
> I wish you the best of luck with your app, but I'm not going to merge this PR for now.

Hi Jakob,

Yes I am indeed the developer of this app.  I am not a spam.  The site I provided is the link from the AppStore. How can it have an invalid TLS certificate?

**Comment by bmpro** [comment]
> > Are you the developer of this app?
> > I wanted to check out the app, but the fact that the apps website has an invalid TLS certificate made me a bit suspicious.
> > Also, your Github account profile looks a bit like a spam account.
> > I wish you the best of luck with your app, but I'm not going to merge this PR for now.
> 
> Hi Jakob,
> 
> Yes I am indeed the developer of this app. I am not a spam. The site I provided is the link from the AppStore. How can it have an invalid TLS certificate?

Also the link I provided is https://apps.apple.com/us/app/xtsequel-fast-database-client/id1482992463
I don't see that it has an invalid certificate.  Is this the link you referred to having an invalid TLS certificate?
Our tool is legitimate and has been approved by Apple.

**Comment by bmpro** [comment]
Can you try the following link and see if you still see the certificate issue? https://apps.apple.com/us/app/xtsequel-fast-database-client/id1482992463?mt=12

**Pull request closed without merging**
