### PR TITLE
Bump version numbers to 9.4.3

### PR DESCRIPTION
**Pull request by Tafkas**

### CODE REVIEW

**Comment by jakob** [comment]
Thanks. Does it build with the new version?

**Comment by Tafkas** [comment]
Yes

**Comment by Tafkas** [comment]
In the meantime 9.4.4 came out

**Comment by jakob** [comment]
Thanks for the pull request. I've now updated to 9.4.4.

However, I did not merge this pull request because I also changed the README file to no longer contain the PostgreSQL version (to avoid getting it out of sync)

Jakob

**Pull request closed without merging**
