### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by ogirginc**
Add Homebrew option to install page.

### CODE REVIEW

**Comment by ogirginc** [comment]
Hi @jakob, sorry to tag you! Would you mind give this a quick look as it is a very minor change?

**Comment by tbussmann** [comment]
if we mention the homebrew cask in the documentation, we need to support it and should take responsibility of the formula at https://github.com/Homebrew/homebrew-cask/blob/master/Casks/postgres.rb - not much work but still something to take care of. 

Also, we provide multiple release streams (currently 3 - only latest major PostgreSQL version, latest 3 and all supported). The cask does install the second edition. This might be a good compromise for most users but not for all and is not documented at present. 

Other opinions?

**Comment by jakob** [comment]
I agree with @tbussmann. We don't maintain the brew cask formula, so if we mention it anywhere, we should only mention it with a big disclaimer that it's not an officially supported way of installing.

Also, `brew cask install postgres` is only simple for people who already have homebrew and know what `cask` is. Otherwise it's confusing. If people look at the install docs because something isn't working, and they see that, they might think that installing homebrew might make things work, and then they end up with even more software on their Macs that they don't know how to use.

I think it's worthwhile mentioning somewhere that there is an inofficial cask formula and it's name is "postgres", but I don't know where the best place for that would be. If we do that, we should also take care to point out the difference between `brew cask install postgres` and `brew install postgresql` because the two look similar but do very different things!

**Comment by ogirginc** [comment]
> if we mention the homebrew cask in the documentation, we need to support it and should take responsibility of the formula at https://github.com/Homebrew/homebrew-cask/blob/master/Casks/postgres.rb - not much work but still something to take care of.

Hmm, I am not sure about this. At least in my mind, casks are supported by Homebrew-Cask community not by the apps' creators. 🤔

> Also, we provide multiple release streams (currently 3 - only latest major PostgreSQL version, latest 3 and all supported). The cask does install the second edition. This might be a good compromise for most users but not for all and is not documented at present.

Was not aware of this. Thanks!

> Also, brew cask install postgres is only simple for people who already have homebrew and know what cask is. Otherwise it's confusing. If people look at the install docs because something isn't working, and they see that, they might think that installing homebrew might make things work, and then they end up with even more software on their Macs that they don't know how to use.

I like to believe a developer who works on Mac does know or at least aware of Homebrew. Than again, this might be my wishful thinking. 😁 

> I think it's worthwhile mentioning somewhere that there is an inofficial cask formula and it's name is "postgres", but I don't know where the best place for that would be. If we do that, we should also take care to point out the difference between brew cask install postgres and brew install postgresql because the two look similar but do very different things!

How about adding a subsection like `### Advance Installing` under `## Installing Postgres.app` with all the warnings? Does that make any sense or should I close this PR?

**Comment by jakob** [comment]
I thought about this a bit more. The obvious place to look for the postgres.app cask formula is https://brew.sh. If you type "Postgres.app" in the search box on brew.sh, you'll find the "postgres" formula.

So I don't think it's necessary to distract our users with a link to Homebrew in our docs. Those who use brew cask will know where to look for formulas. Those who don't know brew cask don't need to learn about it to start using Postgres.app.

Thanks a lot for taking the time to write this up, but we're not going to merge it.

**Comment by ogirginc** [comment]
> Thanks a lot for taking the time to write this up, but we're not going to merge it.

Thanks for the clear communication! :)

**Pull request closed without merging**
