### PR TITLE
Bundle wal2json

### LINKED ISSUE #496: Feature request: bundle wal2json
Great app, thanks for making PostgreSQL so easy to install!

I'd like to request that you bundle the `wal2json` output plugin with PostgresApp. It only takes a couple seconds to build, but unfortunately because PostgresApp is built with a specific version of the MacSDKs, users who do not have that SDK installed cannot build against it. (Note many cloud providers such as [Amazon RDS bundle wal2json](https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-rds-postgresql-105-govcloud/).)

For example, the `pg_config` in this user's Postgres.app indicates `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk`, but this user only has `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk` available:

```
+ rm -Rf wal2json
+ git clone https://github.com/eulerto/wal2json.git
Cloning into 'wal2json'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 492 (delta 24), reused 29 (delta 19), pack-reused 449
Receiving objects: 100% (492/492), 203.11 KiB | 3.44 MiB/s, done.
Resolving deltas: 100% (343/343), done.
+ cd wal2json
+ USE_PGXS=1
+ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument  -mmacosx-version-min=10.7  -I. -I./ -I/Applications/Postgres.app/Contents/Versions/10/include/postgresql/server -I/Applications/Postgres.app/Contents/Versions/10/include/postgresql/internal -I/Applications/Postgres.app/Contents/Versions/10/share/icu -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk  -I/Applications/Postgres.app/Contents/Versions/10/include/libxml2  -I/Applications/Postgres.app/Contents/Versions/10/include  -c -o wal2json.o wal2json.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
In file included from wal2json.c:13:
In file included from /Applications/Postgres.app/Contents/Versions/10/include/postgresql/server/postgres.h:47:
/Applications/Postgres.app/Contents/Versions/10/include/postgresql/server/c.h:81:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [wal2json.o] Error 1
```

```
$ ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer//SDKs/
MacOSX.sdk      MacOSX10.14.sdk
```

Installing wal2json is straight-forward (and fast!):

```bash
PATH="/path/to/pg/bin:$PATH"
git clone https://github.com/eulerto/wal2json.git
cd wal2json
USE_PGXS=1 make
USE_PGXS=1 make install
```

### PR DESCRIPTION
**Pull request by singingwolfboy**
Fixes #496

### CODE REVIEW

**Comment by jakob** [comment]
Thanks for the PR!

However, I would like to know how popular wal2json is? Is this something that a significant fraction of Postgres.app users will need?

We include plv8 and PostGIS because they are popular and difficult to build extensions that a lot of people want to use on their Mac. wal2json on the other hand is something that (I assume) only few people actually use, and if you need it chances are you know how to build extensions for PostgreSQL, and building it would be trivial.

In my opinion, the problem in #496 was not that wal2json isn't bundled, but that it was not possible to easily build it yourself!

I don't want to bundle too many extensions with Postgres.app, since every single extension is one more thing I need to check for compatibility before packaging an update.

If someone can convince me that wal2json is of similar importance as plv8 and PostGIS, I'm willing to reconsider.

(Also, please don't add /usr/local/bin to the $PATH in the makefile, and don't commit any unrelated whitespace changes. If you want to clean up source files, please submit a separate PR.)

**Comment by singingwolfboy** [comment]
I submitted this pull request because I'm working on [PostGraphile](https://www.graphile.org/postgraphile/) with @benjie, and it uses `wal2json` for handling subscriptions and live queries. To be honest, I'm not sure how widely used this extension is, and I totally understand your argument about reducing your support burden!

@benjie, what do you think? Do you want to argue that `wal2json` needs to be bundled with Postgres.app? Are you able to build it separately? Should #496 be closed at this point?

(I split out the whitespace changes into #534, so that they can be reviewed and merged separately.)

**Comment by benjie** [comment]
Hard to argue numbers; I think you'd have to ask @eulerto and even then it's likely hard to judge as people typically only reach out to OSS maintainers when they have issues (and wal2json is pretty solid 😉).

I can say it has [a few forks](https://github.com/eulerto/wal2json/network/members), it's [bundled with Amazon RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html) and a number of PostgreSQL Docker images, and it's the [top option on the PostgreSQL wiki logical decoding plugins page](https://wiki.postgresql.org/wiki/Logical_Decoding_Plugins).

It's only a few lines to clone and install so as long as building it against Postgres.app works I don't think it needs to be bundled (regarding #496 I can't say, it was a client that had the issue and they have a different solution in place now).

If it were bundled it'd further encourage me to recommend Postgres.app to Mac-based PostGraphile users, but don't let that sway you too much - I understand the need to keep things lean so you can release more easily!

**Comment by jakob** [comment]
@benjie Thanks for elaborating on the motivation for wal2json. Your arguments convinced me that wal2json would be a useful addition to Postgres.app.

It also looks like building wal2json doesn't add a lot of complexity, so I guess it doesn't really have to be as widely used as PostGIS to justify its addition.

@singingwolfboy Can you rebase the PR and remove the change to `PATH` (I assume that it should build without changing PATH)

**Comment by singingwolfboy** [comment]
@jakob Done!

I added `/usr/local/bin` to the `PATH` so that I could build using Homebrew, instead of Macports. I've reverted those changes, because you're right that they don't belong in this commit. However, you may want to make that change in the future, if you want to support Homebrew. I'm happy to help with that, if you want!

**Comment by singingwolfboy** [comment]
@jakob any updates on getting this merged?

**Pull request merged**
