### PR TITLE
Reindex all databases

### PR DESCRIPTION
**Pull request by Bouke**
The docs suggest to reindex all databases one by one, which is tedious for a non-trivial amount of databases. I feel like the documentation should also point out the `reindex --all` command, which makes this a trivial job.

### CODE REVIEW

**Comment by jakob** [comment]
Thank you!

I think we focussed on the REINDEX SQL command, because we didn't want to require people to be familiar with the command line. I believe it's a common source of confusion with PostgreSQL that some commands are supposed to be executed in psql and others in a shell PostgreSQL.

That doesn't mean I don't want to mention the command line tool at all, but I wonder how to best phrase it to avoid confusion.

Also, the command is called `reindexdb`.

**Comment by Bouke** [comment]
Yeah I quickly whipped something together. The wording is certainly not great. Maybe a mention in the 'advanced' section is acceptable? For me, a quick pointer to that command would've sufficed.

**Comment by mxgrn** [comment]
Isn't it `reindexdb --all`?

**Comment by jakob** [comment]
I've added a note to the docs. Thanks for your help!

**Pull request closed without merging**
